package com.alirsyad.app.utils

enum class ErrorType(
    code: Int,
    name: String
) {
    ERROR_CONNECTION(100, "ERROR_CONNECTION"),
    ERROR_PROCESS_DATA(101, "ERROR_PROCESS_DATA"),
    ERROR_TECHNICAL(102, "ERROR_TECHNICAL"),
    ERROR_SYSTEM(103, "ERROR_SYSTEM"),
    ERROR_REGISTRATION(400, "ERROR_REGISTRATION"),
    ERROR_WAITING_RESET_PASSWORD(400, "ERROR_WAITING_RESET_PASSWORD"),
    ERROR_LOGIN(400, "ERROR_WAITING_RESET_PASSWORD"),
    ERROR_IS_VISITOR(1, "ERROR_IS_VISITOR"),

    UPDATE_VERSION_READY(104, "UPDATE_VERSION_READY"),
    LOGOUT(105, "LOGOUT"),
}